
// ------------------------------------------------------------------------------------------------
// <auto-generated>
//  This code was generated by a C# code generator
//  Generated at 15.08.2017 17:49:08
//
//  Warning: Do not make changes directly to this file; they will get overwritten on the next
//  code generation.
// </auto-generated>
// ------------------------------------------------------------------------------------------------
    
namespace T4Testing
{

  /// <summary>
  /// Supported colors
  /// </summary>
  public enum User : int
  {
		/// <summary>
		/// Undefined (not mapped in database)
		/// </summary>
		Undefined = 0,
		ahmet = 1,
		faik = 2,
		ahmet faik = 3,
		faik ahmet = 4,

  }
    
}
